### ISSUE TITLE
Cache key hash's don't round trip via pickle

### ISSUE THREAD

**Issue by david-waterworth** [tkem/cachetools#162] opened 2020-03-26 22:24 UTC
I'm not sure if this is supported but answers on StackOverlfow indicate it is. When I use pickle to load a cache, the hash of the keys changes. It seems that `cachetools.keys._HashedTuple` doesn't round trip. The code below reproduces for me using Python 3.7.6 on Ubuntu Linux 18.04

You need to run this multiple times. Each time I run, the hash of the key for the same url changes. You can even comment out the call to `request` once you have a cached item. 

PS Just to be clear - this means that after pickle.load() all cache lookups for pickled (key,value) fail.

```
import cachetools
import pickle

try:
    with open("cache.pkl", 'rb') as f:
        cache = pickle.load(f)
except FileNotFoundError:
    cache = cachetools.TTLCache(maxsize=128, ttl=60*60)
    #cache = cachetools.LRUCache(maxsize=128)

def request(url):
    @cachetools.cached(cache)
    def _request(url):
        return None
    return _request(url)

url = 'https://api.darksky.net/forecast/XXX/-37.8136,144.9631,1546261200?units=si&exclude=currently,minutely,daily,alerts,flags'
response = request(url)  

keys = list(cache._Cache__data.keys())
if len(keys)>0:
    print(keys[0])
    print(type(keys[0]))
    print(hash(keys[0]))

with open("cache.pkl", 'wb') as f:
    pickle.dump(cache, f)
```

**Comment by tkem** [comment] 2020-04-01 09:12
Should be fixed since v3.1.1, see #130, #134 for details.

**Closed by tkem** 2020-04-01 09:12 UTC

**Comment by david-waterworth** [comment] 2020-04-02 05:32
@tkem I'm am using 4.0.0, I'll do some more digging and open a new issue as the key hash might be a red herring. 

BTW your example works but the hash of the cache keys is still changing. Maybe this only matters in certain situations which I'm hitting but I've not been able to create a simple reproduction yet

**Comment by tkem** [comment] 2020-04-03 08:58
@david-waterworth: What you observe is simply Python's _hash randomization_. This isn't specific to `cachetools`, but is intended behavior since Python 3.3 or so. Pickling/unpickling `dict` (and therefore, `Cache`) instances should take care of that.
