### ISSUE TITLE
KeyError: (6261778983944192L,)

### ISSUE THREAD

**Issue by jkatrenic** [tkem/cachetools#82] opened 2017-01-16 09:58 UTC
We are facing of the following issue:
`
  File "/base/data/home/apps/s~zomka-1348/6.398468555765469642/lib/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/base/data/home/apps/s~zomka-1348/6.398468555765469642/handlers/dao/user_dao.py", line 29, in get_last_users
    ret.append(handlers.representation.UserSearch.get_by_id(rr.id()))
  File "/base/data/home/apps/s~zomka-1348/6.398468555765469642/lib/cachetools/__init__.py", line 48, in wrapper
    cache[k] = v
  File "/base/data/home/apps/s~zomka-1348/6.398468555765469642/lib/cachetools/ttl.py", line 91, in __setitem__
    self.expire(time)
  File "/base/data/home/apps/s~zomka-1348/6.398468555765469642/lib/cachetools/ttl.py", line 171, in expire
    cache_delitem(self, curr.key)
  File "/base/data/home/apps/s~zomka-1348/6.398468555765469642/lib/cachetools/cache.py", line 64, in __delitem__
    del self.__data[key]
KeyError: (6261778983944192L,)
`

We cache method which returns a long list of users:
`
@cachetools.cached(cachetools.TTLCache(maxsize=50, ttl=900)) # 900 seconds in cache
def get_last_users(sex0, sex1, search_area):
`

and the also each user separately.

**Comment by tkem** [comment] 2017-01-16 13:12
If your code is multithreaded, this is probably a duplicate of #80, and you should add proper locking to cache access.

**Comment by jkatrenic** [comment] 2017-01-16 13:29
Right, our app is multi threaded. Oh, so we need to make a lock manually?

**Comment by tkem** [comment] 2017-01-16 13:35
Yes, when using the `@cached` decorator you can pass a `lock` argument.
Please see http://pythonhosted.org/cachetools/#cachetools.cached (which also contains an example).

**Comment by jkatrenic** [comment] 2017-01-16 13:37
Great, thanks for you help!

**Comment by tkem** [comment] 2017-01-16 19:46
You're welcome!

**Closed by tkem** 2017-01-16 19:46 UTC
Labels: duplicate
